version: "3.8"

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./deep-knowledge-ai-platform
      dockerfile: Dockerfile
    container_name: deep-knowledge-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - api-gateway
    networks:
      - deep-knowledge-network
    env_file:
      - .env
    environment:
      - PORT=3000

  # Backend Main Service
  backend-main:
    build: ./backend-main
    container_name: deep-knowledge-backend-main
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3001"
    depends_on:
      - langchain-python
    env_file:
      - .env
    environment:
      - PORT=3001
    networks:
      - deep-knowledge-network

  # LangChain Python Service (Mới)
  langchain-python:
    build: ./langchain-python-service
    container_name: deep-knowledge-langchain
    restart: unless-stopped
    ports:
      - "${LANGCHAIN_PORT}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    networks:
      - deep-knowledge-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: deep-knowledge-gateway
    restart: unless-stopped
    ports:
      - "${API_GATEWAY_PORT}:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    depends_on:
      - backend-main
      - langchain-python
    networks:
      - deep-knowledge-network

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - deep-knowledge-network

volumes:
  postgres_data:
  redis_data:

networks:
  deep-knowledge-network:
    driver: bridge
