version: "3.8"

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./deep-knowledge-ai-platform
      dockerfile: Dockerfile
    container_name: deep-knowledge-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - deep-knowledge-network
    environment:
      - INTERNAL_API_GATEWAY_URL=http://api-gateway:8080

  # Backend Main Service
  backend-main:
    build: ./backend-main
    container_name: deep-knowledge-backend-main
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      NODE_ENV: production
      JWT_SECRET: kNFNj0uQCVzdBoVKAbAKUUTf0JPtYqlD
      SUPABASE_URL: https://jkykheapwyozbztnntph.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpreWtoZWFwd3lvemJ6dG5udHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzI4NDksImV4cCI6MjA2NjI0ODg0OX0.uikqgQ3dhqEAArc92eoXQXpYEl18-POUsgkIzLmo0z0
      LANGCHAIN_SERVICE_URL: http://langchain-python:5000
      FLOWISE_API_URL: https://cloud.flowiseai.com/api/v1/prediction/3e25445a-0652-45de-8ad6-8e1c78740a8c
      FLOWISE_API_KEY: YQT-c-WYOGuUiRY7YqK5xAgoGvGnVlzKACW1dJEapS4
      OPENAI_API_KEY: "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"
      OPENAI_MODEL: gpt-3.5-turbo
    networks:
      - deep-knowledge-network

  # LangChain Python Service (Mới)
  langchain-python:
    build: ./langchain-python-service
    container_name: deep-knowledge-langchain
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      OPENROUTER_API_KEY: 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
      DEFAULT_MODEL: google/gemini-2.5-flash
      APP_URL: http://localhost:3000
      APP_NAME: "Deep Knowledge AI Platform"
      FORCE_OPENAI: "false"
      OPENAI_API_KEY: "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"
      DATABASE_URL: "postgresql://postgres.jkykheapwyozbztnntph:Thang979712*@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
      REDIS_URL: redis://redis:6379/0
    networks:
      - deep-knowledge-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: deep-knowledge-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
      BACKEND_MAIN_URL: http://backend-main:3001
      LANGCHAIN_SERVICE_URL: http://langchain-python:5000
    depends_on:
      - backend-main
      - langchain-python
    networks:
      - deep-knowledge-network

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - deep-knowledge-network

volumes:
  postgres_data:
  redis_data:

networks:
  deep-knowledge-network:
    driver: bridge
