export const mockAICourseGen = {
  tree_nodes: [
    {
      temp_id: "1",
      title: "Introduction to AI in Online Sales Optimization",
      description:
        "Detailed explanation of Introduction to AI in Online Sales Optimization",
      level: 0,
      requires: [],
      next: ["2"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "1.1",
      title: "Overview of AI's Role in E-commerce",
      description:
        "Detailed explanation of Overview of AI's Role in E-commerce",
      level: 1,
      requires: ["1"],
      next: ["1.2"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "1.1.1",
      title: "Benefits of AI for Sales Efficiency",
      description:
        "Detailed explanation of Benefits of AI for Sales Efficiency",
      level: 2,
      requires: ["1.1"],
      next: ["1.1.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Benefits of AI for Sales Efficiency. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "1.1.2",
      title: "Ethical Considerations and Data Privacy",
      description:
        "Detailed explanation of Ethical Considerations and Data Privacy",
      level: 2,
      requires: ["1.1"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Ethical Considerations and Data Privacy. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "1.2",
      title: "Prerequisites for Implementing AI Tools",
      description:
        "Detailed explanation of Prerequisites for Implementing AI Tools",
      level: 1,
      requires: ["1"],
      next: [],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "1.2.1",
      title: "Basic Understanding of Online Sales Funnels",
      description:
        "Detailed explanation of Basic Understanding of Online Sales Funnels",
      level: 2,
      requires: ["1.2"],
      next: ["1.2.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Basic Understanding of Online Sales Funnels. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "1.2.2",
      title: "Familiarity with Cloud Platforms (e.g., Google Cloud)",
      description:
        "Detailed explanation of Familiarity with Cloud Platforms (e.g., Google Cloud)",
      level: 2,
      requires: ["1.2"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Familiarity with Cloud Platforms (e.g., Google Cloud). Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2",
      title: "Customer Behavior Analysis with Pre-built AI Tools",
      description:
        "Detailed explanation of Customer Behavior Analysis with Pre-built AI Tools",
      level: 0,
      requires: [],
      next: ["3"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.1",
      title: "Data Collection and Integration",
      description: "Detailed explanation of Data Collection and Integration",
      level: 1,
      requires: ["2"],
      next: ["2.2"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.1.1",
      title: "Using Google Analytics AI Features for Traffic Analysis",
      description:
        "Detailed explanation of Using Google Analytics AI Features for Traffic Analysis",
      level: 2,
      requires: ["2.1"],
      next: ["2.1.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Using Google Analytics AI Features for Traffic Analysis. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.1.2",
      title:
        "CRM Data Enrichment with AI-Powered Tools (e.g., Salesforce Einstein)",
      description:
        "Detailed explanation of CRM Data Enrichment with AI-Powered Tools (e.g., Salesforce Einstein)",
      level: 2,
      requires: ["2.1"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về CRM Data Enrichment with AI-Powered Tools (e.g., Salesforce Einstein). Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.2",
      title: "Behavioral Pattern Recognition",
      description: "Detailed explanation of Behavioral Pattern Recognition",
      level: 1,
      requires: ["2"],
      next: ["2.3"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.2.1",
      title: "ChatGPT for Analyzing Customer Support Queries",
      description:
        "Detailed explanation of ChatGPT for Analyzing Customer Support Queries",
      level: 2,
      requires: ["2.2"],
      next: ["2.2.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về ChatGPT for Analyzing Customer Support Queries. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.2.2",
      title: "SaaS Platforms (e.g., Hotjar) for Session Recording and Heatmaps",
      description:
        "Detailed explanation of SaaS Platforms (e.g., Hotjar) for Session Recording and Heatmaps",
      level: 2,
      requires: ["2.2"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về SaaS Platforms (e.g., Hotjar) for Session Recording and Heatmaps. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.3",
      title: "Segmentation and Targeting",
      description: "Detailed explanation of Segmentation and Targeting",
      level: 1,
      requires: ["2"],
      next: [],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.3.1",
      title: "Google Cloud AI for Demographic Clustering",
      description:
        "Detailed explanation of Google Cloud AI for Demographic Clustering",
      level: 2,
      requires: ["2.3"],
      next: ["2.3.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Google Cloud AI for Demographic Clustering. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "2.3.2",
      title:
        "Dynamic Audience Segmentation with Marketing SaaS (e.e., HubSpot)",
      description:
        "Detailed explanation of Dynamic Audience Segmentation with Marketing SaaS (e.g., HubSpot)",
      level: 2,
      requires: ["2.3"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Dynamic Audience Segmentation with Marketing SaaS (e.g., HubSpot). Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3",
      title: "Trend Prediction and Forecasting Using AI",
      description:
        "Detailed explanation of Trend Prediction and Forecasting Using AI",
      level: 0,
      requires: [],
      next: ["4"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.1",
      title: "Sales Trend Analysis",
      description: "Detailed explanation of Sales Trend Analysis",
      level: 1,
      requires: ["3"],
      next: ["3.2"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.1.1",
      title: "Google Cloud AI for Historical Data Forecasting",
      description:
        "Detailed explanation of Google Cloud AI for Historical Data Forecasting",
      level: 2,
      requires: ["3.1"],
      next: ["3.1.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Google Cloud AI for Historical Data Forecasting. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.1.2",
      title: "SaaS Tools (e.g., Tableau AI) for Visualizing Market Trends",
      description:
        "Detailed explanation of SaaS Tools (e.g., Tableau AI) for Visualizing Market Trends",
      level: 2,
      requires: ["3.1"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về SaaS Tools (e.g., Tableau AI) for Visualizing Market Trends. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.2",
      title: "Demand Prediction",
      description: "Detailed explanation of Demand Prediction",
      level: 1,
      requires: ["3"],
      next: ["3.3"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.2.1",
      title: "ChatGPT for Interpreting Social Media Sentiment",
      description:
        "Detailed explanation of ChatGPT for Interpreting Social Media Sentiment",
      level: 2,
      requires: ["3.2"],
      next: ["3.2.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về ChatGPT for Interpreting Social Media Sentiment. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.2.2",
      title: "Pre-built Models in E-commerce Platforms (e.g., Shopify AI)",
      description:
        "Detailed explanation of Pre-built Models in E-commerce Platforms (e.g., Shopify AI)",
      level: 2,
      requires: ["3.2"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Pre-built Models in E-commerce Platforms (e.g., Shopify AI). Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.3",
      title: "Competitor Monitoring",
      description: "Detailed explanation of Competitor Monitoring",
      level: 1,
      requires: ["3"],
      next: [],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.3.1",
      title: "AI-Powered Tools (e.g., SEMrush) for Competitor Pricing Analysis",
      description:
        "Detailed explanation of AI-Powered Tools (e.g., SEMrush) for Competitor Pricing Analysis",
      level: 2,
      requires: ["3.3"],
      next: ["3.3.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về AI-Powered Tools (e.g., SEMrush) for Competitor Pricing Analysis. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "3.3.2",
      title: "ChatGPT for Summarizing Industry Reports",
      description:
        "Detailed explanation of ChatGPT for Summarizing Industry Reports",
      level: 2,
      requires: ["3.3"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về ChatGPT for Summarizing Industry Reports. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4",
      title: "Personalization Strategies Powered by AI",
      description:
        "Detailed explanation of Personalization Strategies Powered by AI",
      level: 0,
      requires: [],
      next: ["5"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.1",
      title: "Dynamic Content Customization",
      description: "Detailed explanation of Dynamic Content Customization",
      level: 1,
      requires: ["4"],
      next: ["4.2"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.1.1",
      title: "Using Dynamic Yield or Optimizely for Product Recommendations",
      description:
        "Detailed explanation of Using Dynamic Yield or Optimizely for Product Recommendations",
      level: 2,
      requires: ["4.1"],
      next: ["4.1.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Using Dynamic Yield or Optimizely for Product Recommendations. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.1.2",
      title: "ChatGPT for Generating Personalized Email Content",
      description:
        "Detailed explanation of ChatGPT for Generating Personalized Email Content",
      level: 2,
      requires: ["4.1"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về ChatGPT for Generating Personalized Email Content. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.2",
      title: "Customer Journey Optimization",
      description: "Detailed explanation of Customer Journey Optimization",
      level: 1,
      requires: ["4"],
      next: ["4.3"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.2.1",
      title: "AI-Driven Chatbots (e.g., Drift) for Real-Time Interaction",
      description:
        "Detailed explanation of AI-Driven Chatbots (e.g., Drift) for Real-Time Interaction",
      level: 2,
      requires: ["4.2"],
      next: ["4.2.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về AI-Driven Chatbots (e.g., Drift) for Real-Time Interaction. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.2.2",
      title: "SaaS Tools (e.g., Klaviyo) for Behavior-Triggered Emails",
      description:
        "Detailed explanation of SaaS Tools (e.g., Klaviyo) for Behavior-Triggered Emails",
      level: 2,
      requires: ["4.2"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về SaaS Tools (e.g., Klaviyo) for Behavior-Triggered Emails. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.3",
      title: "Pricing and Promotion Personalization",
      description:
        "Detailed explanation of Pricing and Promotion Personalization",
      level: 1,
      requires: ["4"],
      next: [],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.3.1",
      title: "Google Cloud AI for Dynamic Pricing Models",
      description:
        "Detailed explanation of Google Cloud AI for Dynamic Pricing Models",
      level: 2,
      requires: ["4.3"],
      next: ["4.3.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Google Cloud AI for Dynamic Pricing Models. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "4.3.2",
      title: "Tools like PriceLabs for AI-Powered Discount Strategies",
      description:
        "Detailed explanation of Tools like PriceLabs for AI-Powered Discount Strategies",
      level: 2,
      requires: ["4.3"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Tools like PriceLabs for AI-Powered Discount Strategies. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5",
      title: "Real-World Application and Best Practices",
      description:
        "Detailed explanation of Real-World Application and Best Practices",
      level: 0,
      requires: [],
      next: [],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.1",
      title: "Case Studies",
      description: "Detailed explanation of Case Studies",
      level: 1,
      requires: ["5"],
      next: ["5.2"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.1.1",
      title: "Optimizing Checkout Flow with Google Analytics AI",
      description:
        "Detailed explanation of Optimizing Checkout Flow with Google Analytics AI",
      level: 2,
      requires: ["5.1"],
      next: ["5.1.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Optimizing Checkout Flow with Google Analytics AI. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.1.2",
      title: "ChatGPT for Reducing Customer Churn",
      description:
        "Detailed explanation of ChatGPT for Reducing Customer Churn",
      level: 2,
      requires: ["5.1"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về ChatGPT for Reducing Customer Churn. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.2",
      title: "Tool Integration Workflows",
      description: "Detailed explanation of Tool Integration Workflows",
      level: 1,
      requires: ["5"],
      next: ["5.3"],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.2.1",
      title: "Connecting ChatGPT to CRM for Lead Scoring",
      description:
        "Detailed explanation of Connecting ChatGPT to CRM for Lead Scoring",
      level: 2,
      requires: ["5.2"],
      next: ["5.2.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Connecting ChatGPT to CRM for Lead Scoring. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.2.2",
      title: "Automating Reports with Google Cloud AI and Tableau",
      description:
        "Detailed explanation of Automating Reports with Google Cloud AI and Tableau",
      level: 2,
      requires: ["5.2"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Automating Reports with Google Cloud AI and Tableau. Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.3",
      title: "Continuous Improvement",
      description: "Detailed explanation of Continuous Improvement",
      level: 1,
      requires: ["5"],
      next: [],
      is_chat_enabled: false,
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.3.1",
      title: "A/B Testing with AI Tools (e.g., VWO)",
      description:
        "Detailed explanation of A/B Testing with AI Tools (e.g., VWO)",
      level: 2,
      requires: ["5.3"],
      next: ["5.3.2"],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về A/B Testing with AI Tools (e.g., VWO). Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
    {
      temp_id: "5.3.2",
      title: "Monitoring AI Performance Metrics (e.g., Accuracy, Engagement)",
      description:
        "Detailed explanation of Monitoring AI Performance Metrics (e.g., Accuracy, Engagement)",
      level: 2,
      requires: ["5.3"],
      next: [],
      is_chat_enabled: true,
      prompt_sample:
        "Giải thích chi tiết về Monitoring AI Performance Metrics (e.g., Accuracy, Engagement). Cung cấp ví dụ cụ thể và hướng dẫn thực hành.",
      position_x: 0,
      position_y: 0,
      is_completed: false,
      created_at: "",
      updated_at: "",
    },
  ],
};
